server:
  port: 8190
  servlet:
    context-path: /medinet
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/medinet_database
    username: postgres
    password: 1234
    hikari:
      idle-timeout: 10000
      connectionTimeout: 20000
      minimumIdle: 10
      maximumPoolSize: 20
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  mail:
    host: smtp.gmail.com
    username: medinet.rezerwacje@gmail.com
    password: waftruquzzmnrgtr
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true