DROP TABLE IF EXISTS doctor CASCADE;
DROP TABLE IF EXISTS address CASCADE;
DROP TABLE IF EXISTS calendar CASCADE;
DROP TABLE IF EXISTS patient CASCADE;
DROP TABLE IF EXISTS appointment CASCADE;
DROP TABLE IF EXISTS flyway_schema_history CASCADE;
