insert into address (country, city, postal_code, street) values ('Poland', 'Kraków', '08-107', '023 Monument Court');
insert into address (country, city, postal_code, street) values ('Poland', 'Kraków', '16-050', '2405 Dahle Center');
insert into address (country, city, postal_code, street) values ('Poland', 'Opole', '17-201', '187 Farragut Court');
insert into address (country, city, postal_code, street) values ('Poland', 'Wrocław', '67-300', '4168 Manley Drive');
insert into address (country, city, postal_code, street) values ('Poland', 'Rzeszów', '78-425', '48 Vahlen Pass');
insert into address (country, city, postal_code, street) values ('Poland', 'Rzeszów', '32-447', '067 Veith Park');
insert into address (country, city, postal_code, street) values ('Poland', 'Opole', '27-552', '02 Jackson Pass');
insert into address (country, city, postal_code, street) values ('Poland', 'Poznań', '63-005', '40525 Gale Terrace');
insert into address (country, city, postal_code, street) values ('Poland', 'Łódź', '37-600', '044 Corben Way');
insert into address (country, city, postal_code, street) values ('Poland', 'Wrocław', '93-524', '7 Rusk Street');
insert into address (country, city, postal_code, street) values ('Poland', 'Rzeszów', '42-793', '7 Stoughton Alley');
insert into address (country, city, postal_code, street) values ('Poland', 'Kraków', '44-290', '99597 Bowman Circle');
insert into address (country, city, postal_code, street) values ('Poland', 'Opole', '47-280', '5624 Gulseth Terrace');
insert into address (country, city, postal_code, street) values ('Poland', 'Rzeszów', '63-301', '484 Texas Crossing');
insert into address (country, city, postal_code, street) values ('Poland', 'Poznań', '37-114', '12207 Bunting Circle');
insert into address (country, city, postal_code, street) values ('Poland', 'Rzeszów', '32-015', '51880 Clemons Court');
insert into address (country, city, postal_code, street) values ('Poland', 'Poznań', '37-750', '8 Russell Drive');
insert into address (country, city, postal_code, street) values ('Poland', 'Opole', '84-239', '05 Northfield Pass');
insert into address (country, city, postal_code, street) values ('Poland', 'Katowice', '08-455', '9705 Farragut Drive');
insert into address (country, city, postal_code, street) values ('Poland', 'Opole', '72-112', '96995 Rigney Alley');
insert into address (country, city, postal_code, street) values ('Poland', 'Warszwa', '83-240', '5 Cottonwood Center');
insert into address (country, city, postal_code, street) values ('Poland', 'Poznań', '64-115', '3036 Badeau Street');
insert into address (country, city, postal_code, street) values ('Poland', 'Gdańsk', '05-509', '39 Sachs Alley');
insert into address (country, city, postal_code, street) values ('Poland', 'Rzeszów', '95-083', '6077 Novick Trail');
insert into address (country, city, postal_code, street) values ('Poland', 'Opole', '47-180', '7 Westridge Park');
insert into address (country, city, postal_code, street) values ('Poland', 'Wrocław', '21-077', '07450 Warner Point');
insert into address (country, city, postal_code, street) values ('Poland', 'Gdańsk', '07-110', '67 Hovde Hill');
insert into address (country, city, postal_code, street) values ('Poland', 'Opole', '18-404', '6199 Onsgard Way');
insert into address (country, city, postal_code, street) values ('Poland', 'Rzeszów', '44-352', '170 Mendota Road');
insert into address (country, city, postal_code, street) values ('Poland', 'Katowice', '67-415', '6 Pankratz Way');
insert into address (country, city, postal_code, street) values ('Poland', 'Katowice', '73-150', '96695 Colorado Trail');
insert into address (country, city, postal_code, street) values ('Poland', 'Poznań', '26-220', '3168 Rutledge Way');
insert into address (country, city, postal_code, street) values ('Poland', 'Łódź', '05-870', '58 Sherman Circle');
insert into address (country, city, postal_code, street) values ('Poland', 'Opole', '21-404', '45760 Bultman Center');
insert into address (country, city, postal_code, street) values ('Poland', 'Łódź', '60-763', '8358 Delladonna Alley');
insert into address (country, city, postal_code, street) values ('Poland', 'Katowice', '41-106', '3 Meadow Ridge Court');
insert into address (country, city, postal_code, street) values ('Poland', 'Kraków', '32-020', '2085 Badeau Parkway');
insert into address (country, city, postal_code, street) values ('Poland', 'Gdańsk', '98-311', '64226 Huxley Crossing');
insert into address (country, city, postal_code, street) values ('Poland', 'Wrocław', '34-382', '796 Carioca Alley');
insert into address (country, city, postal_code, street) values ('Poland', 'Łódź', '66-101', '04983 Mitchell Hill');
insert into address (country, city, postal_code, street) values ('Poland', 'Katowice', '36-062', '4537 Pawling Avenue');
insert into address (country, city, postal_code, street) values ('Poland', 'Katowice', '42-460', '9535 Loftsgordon Avenue');
insert into address (country, city, postal_code, street) values ('Poland', 'Gdańsk', '97-350', '635 Northport Lane');
insert into address (country, city, postal_code, street) values ('Poland', 'Gdańsk', '83-430', '774 Barby Drive');
insert into address (country, city, postal_code, street) values ('Poland', 'Warszwa', '21-543', '186 Graceland Hill');
insert into address (country, city, postal_code, street) values ('Poland', 'Warszwa', '43-424', '36591 Harper Way');
insert into address (country, city, postal_code, street) values ('Poland', 'Katowice', '34-125', '81 Lunder Way');
insert into address (country, city, postal_code, street) values ('Poland', 'Łódź', '20-960', '7 Blaine Park');
insert into address (country, city, postal_code, street) values ('Poland', 'Łódź', '11-414', '0910 Kings Road');
insert into address (country, city, postal_code, street) values ('Poland', 'Kraków', '87-207', '339 Everett Center');
insert into address (country, city, postal_code, street) values ('Poland', 'Kraków', '34-331', '332 Mesta Hill');
insert into address (country, city, postal_code, street) values ('Poland', 'Gdańsk', '49-200', '59 Debra Park');
insert into address (country, city, postal_code, street) values ('Poland', 'Kraków', '83-262', '54235 Marcy Terrace');
insert into address (country, city, postal_code, street) values ('Poland', 'Katowice', '38-116', '75572 Fremont Avenue');
insert into address (country, city, postal_code, street) values ('Poland', 'Gdańsk', '83-425', '2975 Corscot Crossing');
insert into address (country, city, postal_code, street) values ('Poland', 'Rzeszów', '07-215', '035 Delaware Drive');
insert into address (country, city, postal_code, street) values ('Poland', 'Kraków', '76-153', '9 Manley Place');
insert into address (country, city, postal_code, street) values ('Poland', 'Opole', '63-435', '484 Donald Center');
insert into address (country, city, postal_code, street) values ('Poland', 'Opole', '32-640', '584 New Castle Drive');
insert into address (country, city, postal_code, street) values ('Poland', 'Katowice', '26-803', '7904 Northview Circle');
insert into address (country, city, postal_code, street) values ('Poland', 'Gdańsk', '42-284', '3058 Chinook Drive');
insert into address (country, city, postal_code, street) values ('Poland', 'Opole', '05-804', '1475 Kropf Point');
insert into address (country, city, postal_code, street) values ('Poland', 'Rzeszów', '38-114', '7140 Cordelia Court');
insert into address (country, city, postal_code, street) values ('Poland', 'Poznań', '46-320', '0772 Huxley Circle');
insert into address (country, city, postal_code, street) values ('Poland', 'Poznań', '32-020', '2437 Warbler Point');
insert into address (country, city, postal_code, street) values ('Poland', 'Łódź', '22-120', '3 Del Sol Court');
insert into address (country, city, postal_code, street) values ('Poland', 'Rzeszów', '61-710', '22485 Sheridan Street');
insert into address (country, city, postal_code, street) values ('Poland', 'Poznań', '47-340', '60 Kenwood Place');
insert into address (country, city, postal_code, street) values ('Poland', 'Wrocław', '05-650', '59435 Declaration Crossing');
insert into address (country, city, postal_code, street) values ('Poland', 'Katowice', '98-430', '60 Parkside Road');
insert into address (country, city, postal_code, street) values ('Poland', 'Opole', '87-220', '5 Dwight Circle');
insert into address (country, city, postal_code, street) values ('Poland', 'Gdańsk', '34-206', '0 Rutledge Place');
insert into address (country, city, postal_code, street) values ('Poland', 'Kraków', '26-050', '95208 Tennyson Trail');
insert into address (country, city, postal_code, street) values ('Poland', 'Wrocław', '05-340', '068 Waubesa Lane');
insert into address (country, city, postal_code, street) values ('Poland', 'Warszwa', '72-203', '302 Meadow Ridge Point');
insert into address (country, city, postal_code, street) values ('Poland', 'Gdańsk', '78-410', '09 Stephen Junction');
insert into address (country, city, postal_code, street) values ('Poland', 'Opole', '86-055', '59643 Del Sol Trail');
insert into address (country, city, postal_code, street) values ('Poland', 'Łódź', '58-562', '622 Prairie Rose Junction');
insert into address (country, city, postal_code, street) values ('Poland', 'Kraków', '08-220', '3 Jenifer Alley');
insert into address (country, city, postal_code, street) values ('Poland', 'Rzeszów', '63-642', '50 Talisman Crossing');
insert into address (country, city, postal_code, street) values ('Poland', 'Gdańsk', '14-401', '14 Ramsey Center');
insert into address (country, city, postal_code, street) values ('Poland', 'Katowice', '15-134', '9943 Rigney Point');
insert into address (country, city, postal_code, street) values ('Poland', 'Gdańsk', '78-449', '950 Donald Junction');
insert into address (country, city, postal_code, street) values ('Poland', 'Kraków', '78-530', '3 Graceland Road');
insert into address (country, city, postal_code, street) values ('Poland', 'Poznań', '83-340', '26967 Marcy Alley');
insert into address (country, city, postal_code, street) values ('Poland', 'Kraków', '83-333', '84668 Pawling Lane');
insert into address (country, city, postal_code, street) values ('Poland', 'Rzeszów', '21-110', '43115 Jana Circle');
insert into address (country, city, postal_code, street) values ('Poland', 'Kraków', '72-022', '1168 Carey Avenue');
insert into address (country, city, postal_code, street) values ('Poland', 'Katowice', '82-420', '3045 Loomis Way');
insert into address (country, city, postal_code, street) values ('Poland', 'Poznań', '26-340', '55 Kings Park');
insert into address (country, city, postal_code, street) values ('Poland', 'Opole', '05-340', '45 Cody Plaza');
insert into address (country, city, postal_code, street) values ('Poland', 'Łódź', '05-620', '1609 Sunfield Point');
insert into address (country, city, postal_code, street) values ('Poland', 'Poznań', '32-851', '08 Blaine Lane');
insert into address (country, city, postal_code, street) values ('Poland', 'Gdańsk', '57-320', '6 Warrior Crossing');
insert into address (country, city, postal_code, street) values ('Poland', 'Poznań', '82-100', '40360 Arapahoe Hill');
insert into address (country, city, postal_code, street) values ('Poland', 'Opole', '96-514', '9 Warner Park');
insert into address (country, city, postal_code, street) values ('Poland', 'Kraków', '73-121', '48637 Northview Crossing');
insert into address (country, city, postal_code, street) values ('Poland', 'Gdańsk', '26-806', '24 Packers Place');
insert into address (country, city, postal_code, street) values ('Poland', 'Opole', '89-511', '86 Charing Cross Center');
insert into address (country, city, postal_code, street) values ('Poland', 'Poznań', '43-254', '119 Utah Court');


insert into doctor (name, surname, email, price_for_visit, specialization, address_id) values ('Ralf', 'D''Ambrosio', 'rdambrosio0@dmoz.org', 144.58, 'Seksuolog', 1);
insert into doctor (name, surname, email, price_for_visit, specialization, address_id) values ('Curry', 'Woolfall', 'cwoolfall1@icio.us', 98.32, 'Okulista', 2);
insert into doctor (name, surname, email, price_for_visit, specialization, address_id) values ('Miner', 'Duffin', 'mduffin2@unblog.fr', 259.09, 'Dermatolog', 3);
insert into doctor (name, surname, email, price_for_visit, specialization, address_id) values ('Olivette', 'Pinckstone', 'opinckstone3@techcrunch.com', 105.9, 'Pediatra', 4);
insert into doctor (name, surname, email, price_for_visit, specialization, address_id) values ('Kacie', 'MacPike', 'kmacpike4@flavors.me', 268.57, 'Kardiolog', 5);
insert into doctor (name, surname, email, price_for_visit, specialization, address_id) values ('Venita', 'Radclyffe', 'vradclyffe5@google.co.uk', 162.46, 'Laryngolog', 6);
insert into doctor (name, surname, email, price_for_visit, specialization, address_id) values ('Maxwell', 'Pagon', 'mpagon6@google.com.au', 233.01, 'Chirurg', 7);
insert into doctor (name, surname, email, price_for_visit, specialization, address_id) values ('Wilden', 'Firpo', 'wfirpo7@hubpages.com', 96.4, 'Seksuolog', 8);
insert into doctor (name, surname, email, price_for_visit, specialization, address_id) values ('Say', 'Corstorphine', 'scorstorphine8@seattletimes.com', 89.36, 'Laryngolog', 9);
insert into doctor (name, surname, email, price_for_visit, specialization, address_id) values ('Staford', 'Beloe', 'sbeloe9@buzzfeed.com', 179.05, 'Dermatolog', 10);
insert into doctor (name, surname, email, price_for_visit, specialization, address_id) values ('Chelsae', 'de Vaen', 'cdevaena@vistaprint.com', 271.15, 'Pediatra', 11);
insert into doctor (name, surname, email, price_for_visit, specialization, address_id) values ('Angel', 'Bosley', 'abosleyb@ehow.com', 158.13, 'Dermatolog', 12);
insert into doctor (name, surname, email, price_for_visit, specialization, address_id) values ('Andriana', 'Thackham', 'athackhamc@myspace.com', 265.33, 'Dermatolog', 13);
insert into doctor (name, surname, email, price_for_visit, specialization, address_id) values ('Liane', 'Goymer', 'lgoymerd@tamu.edu', 147.96, 'Kardiolog', 14);
insert into doctor (name, surname, email, price_for_visit, specialization, address_id) values ('Sybyl', 'Chaulk', 'schaulke@jimdo.com', 253.7, 'Okulista', 15);
insert into doctor (name, surname, email, price_for_visit, specialization, address_id) values ('Mella', 'Gauson', 'mgausonf@wix.com', 248.18, 'Pediatra', 16);
insert into doctor (name, surname, email, price_for_visit, specialization, address_id) values ('Basia', 'Southan', 'bsouthang@princeton.edu', 165.93, 'Seksuolog', 17);
insert into doctor (name, surname, email, price_for_visit, specialization, address_id) values ('Cozmo', 'Biggadike', 'cbiggadikeh@photobucket.com', 260.34, 'Seksuolog', 18);
insert into doctor (name, surname, email, price_for_visit, specialization, address_id) values ('Tricia', 'Sallnow', 'tsallnowi@walmart.com', 99.25, 'Seksuolog', 19);
insert into doctor (name, surname, email, price_for_visit, specialization, address_id) values ('Lana', 'Dyet', 'ldyetj@imageshack.us', 240.25, 'Okulista', 20);
insert into doctor (name, surname, email, price_for_visit, specialization, address_id) values ('Tarra', 'Navein', 'tnaveink@g.co', 195.37, 'Chirurg', 21);
insert into doctor (name, surname, email, price_for_visit, specialization, address_id) values ('Janeta', 'Durie', 'jduriel@loc.gov', 102.82, 'Kardiolog', 22);
insert into doctor (name, surname, email, price_for_visit, specialization, address_id) values ('Roley', 'Screeton', 'rscreetonm@latimes.com', 96.63, 'Laryngolog', 23);
insert into doctor (name, surname, email, price_for_visit, specialization, address_id) values ('Berthe', 'Bratley', 'bbratleyn@intel.com', 273.8, 'Dermatolog', 24);
insert into doctor (name, surname, email, price_for_visit, specialization, address_id) values ('Jefferey', 'Jerrim', 'jjerrimo@163.com', 229.66, 'Kardiolog', 25);
insert into doctor (name, surname, email, price_for_visit, specialization, address_id) values ('Roger', 'Haigh', 'rhaighp@businessweek.com', 219.95, 'Dermatolog', 26);
insert into doctor (name, surname, email, price_for_visit, specialization, address_id) values ('Dar', 'Paggitt', 'dpaggittq@etsy.com', 106.88, 'Psycholog', 27);
insert into doctor (name, surname, email, price_for_visit, specialization, address_id) values ('Javier', 'Scarlett', 'jscarlettr@gnu.org', 93.12, 'Okulista', 28);
insert into doctor (name, surname, email, price_for_visit, specialization, address_id) values ('Issiah', 'Edington', 'iedingtons@printfriendly.com', 122.85, 'Laryngolog', 29);
insert into doctor (name, surname, email, price_for_visit, specialization, address_id) values ('Annelise', 'Escalero', 'aescalerot@gizmodo.com', 248.33, 'Seksuolog', 30);
insert into doctor (name, surname, email, price_for_visit, specialization, address_id) values ('Caryn', 'Chern', 'cchernu@google.ca', 233.67, 'Dermatolog', 31);
insert into doctor (name, surname, email, price_for_visit, specialization, address_id) values ('Randene', 'Bennallck', 'rbennallckv@fda.gov', 158.81, 'Psycholog', 32);
insert into doctor (name, surname, email, price_for_visit, specialization, address_id) values ('Sybila', 'Jacobsson', 'sjacobssonw@zdnet.com', 141.84, 'Pediatra', 33);
insert into doctor (name, surname, email, price_for_visit, specialization, address_id) values ('Delinda', 'Trobe', 'dtrobex@weebly.com', 229.34, 'Psycholog', 34);
insert into doctor (name, surname, email, price_for_visit, specialization, address_id) values ('Floria', 'Hartnell', 'fhartnelly@naver.com', 87.92, 'Seksuolog', 35);
insert into doctor (name, surname, email, price_for_visit, specialization, address_id) values ('Allix', 'Jahndel', 'ajahndelz@berkeley.edu', 174.14, 'Seksuolog', 36);
insert into doctor (name, surname, email, price_for_visit, specialization, address_id) values ('Ignace', 'Hutchens', 'ihutchens10@utexas.edu', 171.8, 'Seksuolog', 37);
insert into doctor (name, surname, email, price_for_visit, specialization, address_id) values ('Ewen', 'Woodfin', 'ewoodfin11@yelp.com', 196.12, 'Okulista', 38);
insert into doctor (name, surname, email, price_for_visit, specialization, address_id) values ('Marabel', 'Culvey', 'mculvey12@hibu.com', 270.83, 'Dermatolog', 39);
insert into doctor (name, surname, email, price_for_visit, specialization, address_id) values ('Aldous', 'Whotton', 'awhotton13@shinystat.com', 293.94, 'Seksuolog', 40);
insert into doctor (name, surname, email, price_for_visit, specialization, address_id) values ('Denys', 'Alvarado', 'dalvarado14@cornell.edu', 145.72, 'Pediatra', 41);
insert into doctor (name, surname, email, price_for_visit, specialization, address_id) values ('Daryle', 'Stovold', 'dstovold15@unesco.org', 82.96, 'Okulista', 42);
insert into doctor (name, surname, email, price_for_visit, specialization, address_id) values ('Artemas', 'Charlewood', 'acharlewood16@1688.com', 290.8, 'Pediatra', 43);
insert into doctor (name, surname, email, price_for_visit, specialization, address_id) values ('Dacy', 'Brewett', 'dbrewett17@histats.com', 218.85, 'Psycholog', 44);
insert into doctor (name, surname, email, price_for_visit, specialization, address_id) values ('Savina', 'Giffon', 'sgiffon18@salon.com', 296.34, 'Okulista', 45);
insert into doctor (name, surname, email, price_for_visit, specialization, address_id) values ('Jefferson', 'Kier', 'jkier19@google.com', 298.4, 'Kardiolog', 46);
insert into doctor (name, surname, email, price_for_visit, specialization, address_id) values ('Corinna', 'Tink', 'ctink1a@ucoz.ru', 109.18, 'Kardiolog', 47);
insert into doctor (name, surname, email, price_for_visit, specialization, address_id) values ('Ephrem', 'Dempsey', 'edempsey1b@yelp.com', 220.61, 'Chirurg', 48);
insert into doctor (name, surname, email, price_for_visit, specialization, address_id) values ('Patricio', 'Langthorn', 'plangthorn1c@ask.com', 113.8, 'Seksuolog', 49);
insert into doctor (name, surname, email, price_for_visit, specialization, address_id) values ('Bobina', 'Sheal', 'bsheal1d@sakura.ne.jp', 287.76, 'Psycholog', 50);
insert into doctor (name, surname, email, price_for_visit, specialization, address_id) values ('Fawnia', 'Dumsday', 'fdumsday1e@typepad.com', 277.67, 'Psycholog', 51);
insert into doctor (name, surname, email, price_for_visit, specialization, address_id) values ('Franciskus', 'Baniard', 'fbaniard1f@dagondesign.com', 92.74, 'Seksuolog', 52);
insert into doctor (name, surname, email, price_for_visit, specialization, address_id) values ('Remus', 'Copestake', 'rcopestake1g@admin.ch', 270.5, 'Psycholog', 53);
insert into doctor (name, surname, email, price_for_visit, specialization, address_id) values ('Traci', 'Andress', 'tandress1h@ed.gov', 192.69, 'Chirurg', 54);
insert into doctor (name, surname, email, price_for_visit, specialization, address_id) values ('Rachael', 'Ivanchenkov', 'rivanchenkov1i@arstechnica.com', 231.04, 'Seksuolog', 55);
insert into doctor (name, surname, email, price_for_visit, specialization, address_id) values ('Ambros', 'Ondricek', 'aondricek1j@youku.com', 147.66, 'Kardiolog', 56);
insert into doctor (name, surname, email, price_for_visit, specialization, address_id) values ('Arvie', 'Haggarth', 'ahaggarth1k@i2i.jp', 206.11, 'Pediatra', 57);
insert into doctor (name, surname, email, price_for_visit, specialization, address_id) values ('Freddy', 'Osichev', 'fosichev1l@marriott.com', 255.88, 'Seksuolog', 58);
insert into doctor (name, surname, email, price_for_visit, specialization, address_id) values ('Alexis', 'Borrington', 'aborrington1m@utexas.edu', 113.21, 'Kardiolog', 59);
insert into doctor (name, surname, email, price_for_visit, specialization, address_id) values ('Heida', 'Wildber', 'hwildber1n@scificamerican.com', 188.69, 'Psycholog', 60);
insert into doctor (name, surname, email, price_for_visit, specialization, address_id) values ('Gregg', 'Blazewski', 'gblazewski1o@shareasale.com', 159.12, 'Laryngolog', 61);
insert into doctor (name, surname, email, price_for_visit, specialization, address_id) values ('Florry', 'Monsey', 'fmonsey1p@goo.gl', 266.3, 'Laryngolog', 62);
insert into doctor (name, surname, email, price_for_visit, specialization, address_id) values ('Neil', 'Gokes', 'ngokes1q@irs.gov', 267.85, 'Chirurg', 63);
insert into doctor (name, surname, email, price_for_visit, specialization, address_id) values ('Fanchon', 'Gandey', 'fgandey1r@chronoengine.com', 144.56, 'Psycholog', 64);
insert into doctor (name, surname, email, price_for_visit, specialization, address_id) values ('Shellie', 'Harback', 'sharback1s@japanpost.jp', 128.0, 'Pediatra', 65);
insert into doctor (name, surname, email, price_for_visit, specialization, address_id) values ('Erma', 'Elie', 'eelie1t@discovery.com', 109.66, 'Kardiolog', 66);
insert into doctor (name, surname, email, price_for_visit, specialization, address_id) values ('Fergus', 'Nockells', 'fnockells1u@baidu.com', 110.97, 'Pediatra', 67);
insert into doctor (name, surname, email, price_for_visit, specialization, address_id) values ('Zsa zsa', 'Clausewitz', 'zclausewitz1v@theguardian.com', 231.26, 'Ginekolog', 68);
insert into doctor (name, surname, email, price_for_visit, specialization, address_id) values ('Marietta', 'Treweke', 'mtreweke1w@fc2.com', 298.07, 'Kardiolog', 69);
insert into doctor (name, surname, email, price_for_visit, specialization, address_id) values ('Eadie', 'Dury', 'edury1x@exblog.jp', 121.92, 'Chirurg', 70);
insert into doctor (name, surname, email, price_for_visit, specialization, address_id) values ('Raimund', 'Wiszniewski', 'rwiszniewski1y@biglobe.ne.jp', 271.51, 'Laryngolog', 71);
insert into doctor (name, surname, email, price_for_visit, specialization, address_id) values ('Percival', 'Hasnip', 'phasnip1z@xing.com', 260.64, 'Laryngolog', 72);
insert into doctor (name, surname, email, price_for_visit, specialization, address_id) values ('Annabelle', 'Nassie', 'anassie20@trellian.com', 220.34, 'Ginekolog', 73);
insert into doctor (name, surname, email, price_for_visit, specialization, address_id) values ('Reinaldos', 'Townley', 'rtownley21@mlb.com', 141.35, 'Dermatolog', 74);
insert into doctor (name, surname, email, price_for_visit, specialization, address_id) values ('Isabeau', 'Aizikov', 'iaizikov22@ebay.co.uk', 256.17, 'Okulista', 75);
insert into doctor (name, surname, email, price_for_visit, specialization, address_id) values ('Stafford', 'Snar', 'ssnar23@omniture.com', 260.48, 'Psycholog', 76);
insert into doctor (name, surname, email, price_for_visit, specialization, address_id) values ('Levi', 'Dannatt', 'ldannatt24@upenn.edu', 197.32, 'Psycholog', 77);
insert into doctor (name, surname, email, price_for_visit, specialization, address_id) values ('Lexi', 'Bareford', 'lbareford25@moonfruit.com', 232.6, 'Ginekolog', 78);
insert into doctor (name, surname, email, price_for_visit, specialization, address_id) values ('Griswold', 'Olliffe', 'golliffe26@gravatar.com', 95.85, 'Pediatra', 79);
insert into doctor (name, surname, email, price_for_visit, specialization, address_id) values ('Jori', 'Stubley', 'jstubley27@cocolog-nifty.com', 293.03, 'Chirurg', 80);
insert into doctor (name, surname, email, price_for_visit, specialization, address_id) values ('Hobard', 'Wheelton', 'hwheelton28@woothemes.com', 134.53, 'Laryngolog', 81);
insert into doctor (name, surname, email, price_for_visit, specialization, address_id) values ('Blinnie', 'Boggon', 'bboggon29@e-recht24.de', 120.61, 'Okulista', 82);
insert into doctor (name, surname, email, price_for_visit, specialization, address_id) values ('Fan', 'Hitscher', 'fhitscher2a@google.nl', 82.25, 'Laryngolog', 83);
insert into doctor (name, surname, email, price_for_visit, specialization, address_id) values ('Kaela', 'Ryrie', 'kryrie2b@psu.edu', 82.59, 'Chirurg', 84);
insert into doctor (name, surname, email, price_for_visit, specialization, address_id) values ('Elvis', 'Cathro', 'ecathro2c@hatena.ne.jp', 111.43, 'Okulista', 85);
insert into doctor (name, surname, email, price_for_visit, specialization, address_id) values ('Jessey', 'Sayle', 'jsayle2d@bluehost.com', 251.65, 'Laryngolog', 86);
insert into doctor (name, surname, email, price_for_visit, specialization, address_id) values ('Ayn', 'Verbruggen', 'averbruggen2e@hhs.gov', 128.03, 'Dermatolog', 87);
insert into doctor (name, surname, email, price_for_visit, specialization, address_id) values ('Wain', 'Isselee', 'wisselee2f@netlog.com', 285.25, 'Okulista', 88);
insert into doctor (name, surname, email, price_for_visit, specialization, address_id) values ('Cathi', 'Luto', 'cluto2g@infoseek.co.jp', 172.68, 'Kardiolog', 89);
insert into doctor (name, surname, email, price_for_visit, specialization, address_id) values ('Noelani', 'Garnson', 'ngarnson2h@ihg.com', 196.45, 'Seksuolog', 90);
insert into doctor (name, surname, email, price_for_visit, specialization, address_id) values ('Randene', 'De Biasi', 'rdebiasi2i@globo.com', 202.04, 'Psycholog', 91);
insert into doctor (name, surname, email, price_for_visit, specialization, address_id) values ('Janean', 'Inglese', 'jinglese2j@umich.edu', 113.28, 'Kardiolog', 92);
insert into doctor (name, surname, email, price_for_visit, specialization, address_id) values ('Deerdre', 'Ortas', 'dortas2k@loc.gov', 229.13, 'Seksuolog', 93);
insert into doctor (name, surname, email, price_for_visit, specialization, address_id) values ('Dallas', 'Birtles', 'dbirtles2l@zimbio.com', 243.31, 'Okulista', 94);
insert into doctor (name, surname, email, price_for_visit, specialization, address_id) values ('Kaine', 'McGroarty', 'kmcgroarty2m@acquirethisname.com', 176.13, 'Dermatolog', 95);
insert into doctor (name, surname, email, price_for_visit, specialization, address_id) values ('Moises', 'Martensen', 'mmartensen2n@goo.gl', 279.85, 'Laryngolog', 96);
insert into doctor (name, surname, email, price_for_visit, specialization, address_id) values ('Ebenezer', 'Regus', 'eregus2o@bing.com', 197.54, 'Okulista', 97);
insert into doctor (name, surname, email, price_for_visit, specialization, address_id) values ('Neysa', 'Wimpenny', 'nwimpenny2p@yelp.com', 139.38, 'Kardiolog', 98);
insert into doctor (name, surname, email, price_for_visit, specialization, address_id) values ('Tiebold', 'Gladdin', 'tgladdin2q@odnoklassniki.ru', 260.14, 'Okulista', 99);
insert into doctor (name, surname, email, price_for_visit, specialization, address_id) values ('Talia', 'Joanic', 'tjoanic2r@zdnet.com', 102.03, 'Kardiolog', 100);

insert into calendar(doctor_id, date, hours) values (1, '2023-07-02', (ARRAY['8:00', '12:00']));
insert into calendar(doctor_id, date, hours) values (1, '2023-08-02', (ARRAY['8:00', '12:00']));
insert into calendar(doctor_id, date, hours) values (1, '2023-08-03', (ARRAY['9:00', '12:00', '14:00']));
insert into calendar(doctor_id, date, hours) values (1, '2023-08-04', (ARRAY['10:00', '12:00']));
insert into calendar(doctor_id, date, hours) values (1, '2023-08-05', (ARRAY['8:00', '12:00']));


insert into calendar(doctor_id, date, hours) values (2, '2024-08-13', (ARRAY['9:00', '12:00']));
insert into calendar(doctor_id, date, hours) values (2, '2024-08-14', (ARRAY['10:00', '12:00', '16:00']));
insert into calendar(doctor_id, date, hours) values (2, '2024-08-15', (ARRAY['8:00', '12:00']));
insert into calendar(doctor_id, date, hours) values (2, '2024-08-16', (ARRAY['13:00', '14:00']));
insert into calendar(doctor_id, date, hours) values (2, '2024-08-18', (ARRAY['8:00', '12:00']));
insert into calendar(doctor_id, date, hours) values (2, '2024-08-19', (ARRAY['8:00', '12:00']));
insert into calendar(doctor_id, date, hours) values (2, '2024-08-20', (ARRAY['8:00', '12:00']));
--
-- UPDATE calendar
-- SET hours = hours || ARRAY['9:00']
-- WHERE doctor_id = 1 -- identyfikator lekarza
--   AND date = '2024-08-12';
