insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (1, 1, 1, CURRENT_TIMESTAMP, 'daje 5 gwiazdek');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (2, 2, 2, CURRENT_TIMESTAMP, 'elegancko');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (3, 3, 3, CURRENT_TIMESTAMP, 'daje 5 gwiazdek');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (4, 4, 4, CURRENT_TIMESTAMP, 'daje 5 gwiazdek');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (5, 5, 5, CURRENT_TIMESTAMP, 'hej');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (6, 6, 6, CURRENT_TIMESTAMP, 'daje 5 gwiazdek');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (7, 7, 7, CURRENT_TIMESTAMP, 'elegancko');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (8, 8, 8, CURRENT_TIMESTAMP, 'hej');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (9, 9, 9, CURRENT_TIMESTAMP, 'fajnie');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (10, 10, 10, CURRENT_TIMESTAMP, 'fajnie');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (11, 11, 11, CURRENT_TIMESTAMP, 'elegancko');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (12, 12, 12, CURRENT_TIMESTAMP, 'elegancko');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (13, 13, 13, CURRENT_TIMESTAMP, 'hej');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (14, 14, 14, CURRENT_TIMESTAMP, 'elegancko');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (15, 15, 15, CURRENT_TIMESTAMP, 'hej');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (16, 16, 16, CURRENT_TIMESTAMP, 'hej');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (17, 17, 17, CURRENT_TIMESTAMP, 'daje 5 gwiazdek');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (18, 18, 18, CURRENT_TIMESTAMP, 'daje 5 gwiazdek');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (19, 19, 19, CURRENT_TIMESTAMP, 'hej');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (20, 20, 20, CURRENT_TIMESTAMP, 'hej');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (21, 21, 21, CURRENT_TIMESTAMP, 'hej');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (22, 22, 22, CURRENT_TIMESTAMP, 'daje 5 gwiazdek');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (23, 23, 23, CURRENT_TIMESTAMP, 'hej');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (24, 24, 24, CURRENT_TIMESTAMP, 'daje 5 gwiazdek');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (25, 25, 25, CURRENT_TIMESTAMP, 'hej');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (26, 26, 26, CURRENT_TIMESTAMP, 'fajnie');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (27, 27, 27, CURRENT_TIMESTAMP, 'fajnie');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (28, 28, 28, CURRENT_TIMESTAMP, 'elegancko');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (29, 29, 29, CURRENT_TIMESTAMP, 'fajnie');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (30, 30, 30, CURRENT_TIMESTAMP, 'elegancko');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (31, 31, 31, CURRENT_TIMESTAMP, 'elegancko');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (32, 32, 32, CURRENT_TIMESTAMP, 'elegancko');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (33, 33, 33, CURRENT_TIMESTAMP, 'elegancko');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (34, 34, 34, CURRENT_TIMESTAMP, 'elegancko');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (35, 35, 35, CURRENT_TIMESTAMP, 'daje 5 gwiazdek');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (36, 36, 36, CURRENT_TIMESTAMP, 'daje 5 gwiazdek');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (37, 37, 37, CURRENT_TIMESTAMP, 'elegancko');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (38, 38, 38, CURRENT_TIMESTAMP, 'daje 5 gwiazdek');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (39, 39, 39, CURRENT_TIMESTAMP, 'fajnie');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (40, 40, 40, CURRENT_TIMESTAMP, 'daje 5 gwiazdek');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (41, 41, 41, CURRENT_TIMESTAMP, 'elegancko');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (42, 42, 42, CURRENT_TIMESTAMP, 'daje 5 gwiazdek');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (43, 43, 43, CURRENT_TIMESTAMP, 'daje 5 gwiazdek');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (44, 44, 44, CURRENT_TIMESTAMP, 'fajnie');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (45, 45, 45, CURRENT_TIMESTAMP, 'daje 5 gwiazdek');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (46, 46, 46, CURRENT_TIMESTAMP, 'fajnie');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (47, 47, 47, CURRENT_TIMESTAMP, 'hej');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (48, 48, 48, CURRENT_TIMESTAMP, 'hej');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (49, 49, 49, CURRENT_TIMESTAMP, 'daje 5 gwiazdek');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (50, 50, 50, CURRENT_TIMESTAMP, 'daje 5 gwiazdek');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (51, 51, 51, CURRENT_TIMESTAMP, 'elegancko');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (52, 52, 52, CURRENT_TIMESTAMP, 'hej');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (53, 53, 53, CURRENT_TIMESTAMP, 'elegancko');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (54, 54, 54, CURRENT_TIMESTAMP, 'daje 5 gwiazdek');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (55, 55, 55, CURRENT_TIMESTAMP, 'fajnie');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (56, 56, 56, CURRENT_TIMESTAMP, 'elegancko');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (57, 57, 57, CURRENT_TIMESTAMP, 'fajnie');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (58, 58, 58, CURRENT_TIMESTAMP, 'fajnie');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (59, 59, 59, CURRENT_TIMESTAMP, 'fajnie');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (60, 60, 60, CURRENT_TIMESTAMP, 'elegancko');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (61, 61, 61, CURRENT_TIMESTAMP, 'hej');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (62, 62, 62, CURRENT_TIMESTAMP, 'daje 5 gwiazdek');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (63, 63, 63, CURRENT_TIMESTAMP, 'elegancko');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (64, 64, 64, CURRENT_TIMESTAMP, 'daje 5 gwiazdek');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (65, 65, 65, CURRENT_TIMESTAMP, 'daje 5 gwiazdek');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (66, 66, 66, CURRENT_TIMESTAMP, 'fajnie');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (67, 67, 67, CURRENT_TIMESTAMP, 'fajnie');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (68, 68, 68, CURRENT_TIMESTAMP, 'hej');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (69, 69, 69, CURRENT_TIMESTAMP, 'fajnie');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (70, 70, 70, CURRENT_TIMESTAMP, 'daje 5 gwiazdek');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (71, 71, 71, CURRENT_TIMESTAMP, 'elegancko');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (72, 72, 72, CURRENT_TIMESTAMP, 'fajnie');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (73, 73, 73, CURRENT_TIMESTAMP, 'elegancko');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (74, 74, 74, CURRENT_TIMESTAMP, 'fajnie');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (75, 75, 75, CURRENT_TIMESTAMP, 'elegancko');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (76, 76, 76, CURRENT_TIMESTAMP, 'daje 5 gwiazdek');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (77, 77, 77, CURRENT_TIMESTAMP, 'hej');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (78, 78, 78, CURRENT_TIMESTAMP, 'fajnie');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (79, 79, 79, CURRENT_TIMESTAMP, 'daje 5 gwiazdek');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (80, 80, 80, CURRENT_TIMESTAMP, 'daje 5 gwiazdek');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (81, 81, 81, CURRENT_TIMESTAMP, 'daje 5 gwiazdek');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (82, 82, 82, CURRENT_TIMESTAMP, 'elegancko');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (83, 83, 83, CURRENT_TIMESTAMP, 'elegancko');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (84, 84, 84, CURRENT_TIMESTAMP, 'elegancko');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (85, 85, 85, CURRENT_TIMESTAMP, 'elegancko');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (86, 86, 86, CURRENT_TIMESTAMP, 'elegancko');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (87, 87, 87, CURRENT_TIMESTAMP, 'elegancko');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (88, 88, 88, CURRENT_TIMESTAMP, 'fajnie');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (89, 89, 89, CURRENT_TIMESTAMP, 'elegancko');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (90, 90, 90, CURRENT_TIMESTAMP, 'hej');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (91, 91, 91, CURRENT_TIMESTAMP, 'elegancko');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (92, 92, 92, CURRENT_TIMESTAMP, 'hej');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (93, 93, 93, CURRENT_TIMESTAMP, 'daje 5 gwiazdek');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (94, 94, 94, CURRENT_TIMESTAMP, 'hej');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (95, 95, 95, CURRENT_TIMESTAMP, 'elegancko');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (96, 96, 96, CURRENT_TIMESTAMP, 'daje 5 gwiazdek');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (97, 97, 97, CURRENT_TIMESTAMP, 'daje 5 gwiazdek');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (98, 98, 98, CURRENT_TIMESTAMP, 'elegancko');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (99, 99, 99, CURRENT_TIMESTAMP, 'elegancko');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (100, 100, 100, CURRENT_TIMESTAMP, 'hej');