
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (2, 1,2, CURRENT_TIMESTAMP, 'elegancko');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (3, 1,3, CURRENT_TIMESTAMP, 'daje 5 gwiazdek');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (4, 1,4, CURRENT_TIMESTAMP, 'daje 5 gwiazdek');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (5, 1,5, CURRENT_TIMESTAMP, 'hej');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (6, 1,6, CURRENT_TIMESTAMP, 'daje 5 gwiazdek');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (7, 1,7, CURRENT_TIMESTAMP, 'elegancko');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (8, 1,8, CURRENT_TIMESTAMP, 'hej');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (9, 1,9, CURRENT_TIMESTAMP, 'fajnie');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (10, 1,10, CURRENT_TIMESTAMP, 'fajnie');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (11, 1,11, CURRENT_TIMESTAMP, 'elegancko');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (12, 1,12, CURRENT_TIMESTAMP, 'elegancko');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (13, 1,13, CURRENT_TIMESTAMP, 'hej');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (14, 1,14, CURRENT_TIMESTAMP, 'elegancko');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (15, 1,15, CURRENT_TIMESTAMP, 'hej');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (16, 1,16, CURRENT_TIMESTAMP, 'hej');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (17, 1,17, CURRENT_TIMESTAMP, 'daje 5 gwiazdek');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (18, 1,18, CURRENT_TIMESTAMP, 'daje 5 gwiazdek');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (19, 1,19, CURRENT_TIMESTAMP, 'hej');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (20, 1,20, CURRENT_TIMESTAMP, 'hej');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (21, 1,21, CURRENT_TIMESTAMP, 'hej');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (22, 1,22, CURRENT_TIMESTAMP, 'daje 5 gwiazdek');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (23, 1,23, CURRENT_TIMESTAMP, 'hej');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (24, 1,24, CURRENT_TIMESTAMP, 'daje 5 gwiazdek');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (25, 1,25, CURRENT_TIMESTAMP, 'hej');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (26, 1,26, CURRENT_TIMESTAMP, 'fajnie');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (27, 1,27, CURRENT_TIMESTAMP, 'fajnie');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (28, 1,28, CURRENT_TIMESTAMP, 'elegancko');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (29, 1,29, CURRENT_TIMESTAMP, 'fajnie');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (30, 1,30, CURRENT_TIMESTAMP, 'elegancko');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (31, 1,31, CURRENT_TIMESTAMP, 'elegancko');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (32, 1,32, CURRENT_TIMESTAMP, 'elegancko');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (33, 1,33, CURRENT_TIMESTAMP, 'elegancko');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (34, 1,34, CURRENT_TIMESTAMP, 'elegancko');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (35, 1,35, CURRENT_TIMESTAMP, 'daje 5 gwiazdek');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (36, 1,36, CURRENT_TIMESTAMP, 'daje 5 gwiazdek');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (37, 1,37, CURRENT_TIMESTAMP, 'elegancko');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (38, 1,38, CURRENT_TIMESTAMP, 'daje 5 gwiazdek');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (39, 1,39, CURRENT_TIMESTAMP, 'fajnie');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (40, 1,40, CURRENT_TIMESTAMP, 'daje 5 gwiazdek');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (41, 1,41, CURRENT_TIMESTAMP, 'elegancko');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (42, 1,42, CURRENT_TIMESTAMP, 'daje 5 gwiazdek');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (43, 1,43, CURRENT_TIMESTAMP, 'daje 5 gwiazdek');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (44, 1,44, CURRENT_TIMESTAMP, 'fajnie');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (45, 1,45, CURRENT_TIMESTAMP, 'daje 5 gwiazdek');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (46, 1,46, CURRENT_TIMESTAMP, 'fajnie');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (47, 1,47, CURRENT_TIMESTAMP, 'hej');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (48, 1,48, CURRENT_TIMESTAMP, 'hej');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (49, 1,49, CURRENT_TIMESTAMP, 'daje 5 gwiazdek');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (50, 1,50, CURRENT_TIMESTAMP, 'daje 5 gwiazdek');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (51, 1,51, CURRENT_TIMESTAMP, 'elegancko');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (52, 1,52, CURRENT_TIMESTAMP, 'hej');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (53, 1,53, CURRENT_TIMESTAMP, 'elegancko');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (54, 1,54, CURRENT_TIMESTAMP, 'daje 5 gwiazdek');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (55, 1,55, CURRENT_TIMESTAMP, 'fajnie');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (56, 1,56, CURRENT_TIMESTAMP, 'elegancko');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (57, 1,57, CURRENT_TIMESTAMP, 'fajnie');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (58, 1,58, CURRENT_TIMESTAMP, 'fajnie');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (59, 1,59, CURRENT_TIMESTAMP, 'fajnie');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (60, 1,60, CURRENT_TIMESTAMP, 'elegancko');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (61, 1,61, CURRENT_TIMESTAMP, 'hej');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (62, 1,62, CURRENT_TIMESTAMP, 'daje 5 gwiazdek');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (63, 1,63, CURRENT_TIMESTAMP, 'elegancko');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (64, 1,64, CURRENT_TIMESTAMP, 'daje 5 gwiazdek');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (65, 1,65, CURRENT_TIMESTAMP, 'daje 5 gwiazdek');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (66, 1,66, CURRENT_TIMESTAMP, 'fajnie');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (67, 1,67, CURRENT_TIMESTAMP, 'fajnie');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (68, 1,68, CURRENT_TIMESTAMP, 'hej');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (69, 1,69, CURRENT_TIMESTAMP, 'fajnie');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (70, 1,70, CURRENT_TIMESTAMP, 'daje 5 gwiazdek');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (71, 1,71, CURRENT_TIMESTAMP, 'elegancko');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (72, 1,72, CURRENT_TIMESTAMP, 'fajnie');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (73, 1,73, CURRENT_TIMESTAMP, 'elegancko');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (74, 1,74, CURRENT_TIMESTAMP, 'fajnie');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (75, 1,75, CURRENT_TIMESTAMP, 'elegancko');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (76, 1,76, CURRENT_TIMESTAMP, 'daje 5 gwiazdek');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (77, 1,77, CURRENT_TIMESTAMP, 'hej');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (78, 1,78, CURRENT_TIMESTAMP, 'fajnie');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (79, 1,79, CURRENT_TIMESTAMP, 'daje 5 gwiazdek');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (80, 1,80, CURRENT_TIMESTAMP, 'daje 5 gwiazdek');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (81, 1,81, CURRENT_TIMESTAMP, 'daje 5 gwiazdek');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (82, 1,82, CURRENT_TIMESTAMP, 'elegancko');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (83, 1,83, CURRENT_TIMESTAMP, 'elegancko');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (84, 1,84, CURRENT_TIMESTAMP, 'elegancko');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (85, 1,85, CURRENT_TIMESTAMP, 'elegancko');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (86, 1,86, CURRENT_TIMESTAMP, 'elegancko');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (87, 1,87, CURRENT_TIMESTAMP, 'elegancko');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (88, 1,88, CURRENT_TIMESTAMP, 'fajnie');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (89, 1,89, CURRENT_TIMESTAMP, 'elegancko');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (90, 1,90, CURRENT_TIMESTAMP, 'hej');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (91, 1,91, CURRENT_TIMESTAMP, 'elegancko');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (92, 1,92, CURRENT_TIMESTAMP, 'hej');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (93, 1,93, CURRENT_TIMESTAMP, 'daje 5 gwiazdek');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (94, 1,94, CURRENT_TIMESTAMP, 'hej');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (95, 1,95, CURRENT_TIMESTAMP, 'elegancko');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (96, 1,96, CURRENT_TIMESTAMP, 'daje 5 gwiazdek');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (97, 1,97, CURRENT_TIMESTAMP, 'daje 5 gwiazdek');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (98, 1,98, CURRENT_TIMESTAMP, 'elegancko');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (99, 1,99, CURRENT_TIMESTAMP, 'elegancko');
insert into opinion (opinion_id, patient_id, doctor_id, date, note) values (100,1, 100, CURRENT_TIMESTAMP, 'hej');